### ISSUE TITLE
Poster

### ISSUE THREAD

**Issue by keke1022** [keke1022/Informer2020#2]
# Poster Presentation

## Methodology

Use Informer / Vanilla Transformers (Decoder only) / ARIMA to predict the financial sequential data.

## Original Paper

[Informer Paper](https://arxiv.org/abs/2012.07436)

## Innovations

Use Patch / Sentimental analysis to augment data.

## TODOs

- [ ] LSTM
- [ ] Vanilla transformer
- [ ] Informer
- [x] Informer + sentimental features
   - [x] Download Apple news from https://www.kaggle.com/datasets/frankossai/apple-stock-aapl-historical-financial-news-data
   - [x] Change news into sentimental scores (-1 ~ 1) by https://huggingface.co/mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis / Or we can just use the scores provided by the kaggle dataset
   - [x] Use sentimental scores to informer

## Experiments
- [x] Only apple stock price and column (predict itself) mse: 6.86, mae: 2.57
    - [x] add sentimental score as another column mse: 5.46, mae: 2.29
    - [ ] as internal feature
- [x] Use all stock price and apple is target mse: 11.7, mae: 3.39
    - [ ] add sentimental score as another column
    - [ ] as internal feature
    

## Evaluation

Run on [ETT dataset](https://github.com/zhouhaoyi/ETDataset) / [US Stock Price](https://www.kaggle.com/datasets/saketk511/2019-2024-us-stock-market-data/data) w/w.o. patch. 

## Datasets

1. [ETT dataset](https://github.com/zhouhaoyi/ETDataset)
2. [US Stock Price](https://www.kaggle.com/datasets/saketk511/2019-2024-us-stock-market-data/data)
3. [Sentimental Dataset](https://www.kaggle.com/code/mmmarchetti/sentiment-analysis-on-financial-news/notebook)
